kind: Service      # Create new service
apiVersion: v1     
metadata:
  name: music-service # Name of the service (DNS - RFC 2929)
spec:
  selector:
    app: springmusic    # Run on any pod with label - app:myapp
  ports:          # Map incoming port to target port
  - name: tcp-port    # Setting multiple ports listen 
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer  
