apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music-deployment
spec:
  selector:
    matchLabels:
      app: springmusic
  replicas: 2
  template: 
    metadata:
      labels:
        app: springmusic
    spec:
      containers:
      - name: springmusic
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 80


