apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: bear
    image: supergiantkir/animals:bear
    volumeMounts:
    - name: test-volume
      mountPath: /storage
  - name: springapp
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: test-volume
      mountPath: /storage
  volumes:
  - name: app-storage
    hostpath: /tmp
